intd450-w22/descension

Descension/.gitignore, Descension/Assets/Prefab/EnemyPrefab.prefab, Descension/Assets/Prefab/EnemyPrefab.prefab.meta, Descension/Assets/Scenes/TestScenes/EnemyTestScene.unity, Descension/Assets/Scenes/TestScenes/EnemyTestScene.unity.meta, Descension/Assets/Scripts/Actor/AI.meta, Descension/Assets/Scripts/Actor/AI/AIController.cs, Descension/Assets/Scripts/Actor/AI/AIController.cs.meta, Descension/Assets/Scripts/Actor/Player/PlayerController.cs, Descension/Assets/Scripts/Actor/Player/PlayerController.cs.meta, Descension/Assets/Scripts/Util/Util.cs, Descension/ProjectSettings/ProjectSettings.asset, Descension/ProjectSettings/TagManager.asset
basic enemy prefab that patrols between points, and chases the player if it sees them
=> Enemy behaviour

Descension/Assets/Prefab/EnemyPrefab.prefab, Descension/Assets/Scenes/Levels/Level1-AIController.unity, Descension/Assets/Scenes/Levels/Level1-AIController.unity.meta, Descension/Assets/Scripts/Actor/AI/AIController.cs, Descension/Assets/Scripts/Actor/Objects.meta, Descension/Assets/Scripts/Actor/Objects/Projectile.cs, Descension/Assets/Scripts/Actor/Objects/Projectile.cs.meta, Descension/Assets/Scripts/Actor/Player/PlayerController.cs, Descension/Assets/Scripts/Items/Arrow.cs, Descension/Assets/Scripts/Util/Util.cs
Added code from enemyOne to AIController since AIController is set up for more detailed enemy movement. Included an enemy in scene Level1-AIController in position of original enemy as demonstration. Also changed Arrow.cs to call inflictDamage on AIController instead.
=> Demo enemy incorporation

Descension/Assets/Scripts/Actor/Player/PlayerController.cs
Fixed janky collision
Refactored variable names.
=> update movement to physics based, changed variable names

Descension/Assets/Prefab/UI/Menu/MenuItemPrefab.prefab, Descension/Assets/Scenes/GUI/MainMenu.unity, Descension/ProjectSettings/EditorBuildSettings.asset
Update the build settings to include Level 1 and Level 2, fix menu scaling that somehow broke, some QoL prefab work, and add a 'Start Game'
=> Update Main Menu

Descension/Assets/Scenes/Levels/Level1-Perspective.unity, Descension/Assets/Scenes/Levels/Level2-Perspective.unity, Descension/Assets/Scripts/Actor/Player/PlayerController.cs, Descension/Assets/Scripts/Managers/GameManager.cs
> Felipe: @Reilly it seems the menu doesn't work on level 2?
> Reilly: which menu
> Reilly: pause menu ?
> Felipe: yes, it shows up but i can't select options
> Felipe: and movement input doesn't seem to work after i select a level to play from the main menu
> Felipe: and after i restart
=> Fix Input Error

Descension/Assets/Scripts/Items/arrowsItem.cs, Descension/Assets/Scripts/Items/bowItem.cs, Descension/Assets/Scripts/Items/pickItem.cs, Descension/Assets/Scripts/Items/ropeItem.cs, Descension/Assets/Scripts/Items/torchItem.cs
=> Fix bug B)

Descension/Assets/Scenes/Levels/Level1-Perspective.unity
=> Release for Build #4 - BUG FIX

Descension/Assets/Prefab/Actors/PlayerPrefab.prefab, Descension/Assets/Scenes/TestScenes/CombatTestScene.unity, Descension/Assets/Scripts/Actor/AI/AIController.cs, Descension/Assets/Scripts/Actor/Objects/Arrow.cs, Descension/Assets/Scripts/Actor/Player/PlayerController.cs, Descension/Assets/Scripts/Items/Pickups/PickItem.cs
- Switches from using forces on the rigidbody to using the rigidbody's [MovePosition ](https://docs.unity3d.com/ScriptReference/Rigidbody.MovePosition.html) function, which is a feature I didn't know existed.
- I originally was re-writing a CharacterController's Move function to try and emulate it with a rigidbody... I don't know why I never hear people talk about MovePosition o_O hopefully it works well for our purposes, it seems to do everything we want from what I can tell
- Check for IsPaused in a few more places 
- Couple random fixes like sending the gold value to the UI
* Note: UI-related updates will be included in a separate PR
* Note: Combat-related updates will be included in a separate PR; needs some tweaking still
=> Simplify Movement + QoL

Descension/Assets/Prefab/Actors/GuardEnemy.prefab, Descension/Assets/Prefab/Actors/GuardEnemy.prefab.meta, Descension/Assets/Prefab/Actors/PatrollingEnemy.prefab, Descension/Assets/Prefab/Actors/PatrollingEnemy.prefab.meta
Noticed the new levels 1 and 2 just contain stateless enemies, added Guard and Patrolling enemy variants as prefabs.
=> add enemies as prefab

.github/workflows/tests.yml, Descension/Assets/Prefab/GameManagers/ManagersPrefab.prefab, Descension/Assets/Prefab/GameManagers/SoundManagerPrefab.prefab, Descension/Assets/Prefab/Items/Equippables/Sword.prefab, Descension/Assets/Prefab/OnLevelStart.prefab, Descension/Assets/Prefab/OnLevelStart.prefab.meta, Descension/Assets/Scenes/Levels/Level1-Perspective.unity, Descension/Assets/Scenes/Levels/Level2-Perspective.unity, Descension/Assets/Scripts/Actor/AI/AIController.cs, Descension/Assets/Scripts/Actor/Objects/Arrow.cs, Descension/Assets/Scripts/Actor/Player/PlayerController.cs, Descension/Assets/Scripts/Environment/OnLevelStart.cs, Descension/Assets/Scripts/Environment/OnLevelStart.cs.meta, Descension/Assets/Scripts/Items/torchItem.cs, Descension/Assets/Scripts/Managers/DialogueManager.cs, Descension/Assets/Scripts/Managers/GameManager.cs, Descension/Assets/Scripts/Managers/SoundManager.cs, Descension/Assets/Scripts/UI/Controllers/ButtonController/ResumeGameButtonController.cs, Descension/Assets/Scripts/Util/Audio.meta, Descension/Assets/Scripts/Util/Audio/AudioHelper.cs, Descension/Assets/Scripts/Util/Audio/AudioHelper.cs.meta
- Increase sword radius 
- Stop/Start background audio when it makes sense
- Add "OnLevelStart" script to level 1 and 2 that allows for initializing/reinitializingthe level
- Only show torch description once
- Add audio fade in/out utility 
- Add "Frozen" to game manager
- If the game is "Frozen" nobody can move but that game is not paused. Used when dialogues are open
- If the game is "Paused" the pause menu is open 
- You can Pause when in a dialogue
- Formatted `DialogueManager` and `SoundManager`
[DES-91]
[DES-119]
Blocked by #70 
[DES-91]: https://descension.atlassian.net/browse/DES-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DES-119]: https://descension.atlassian.net/browse/DES-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
=> Add Quality of Life Adjustments

Descension/Assets/Prefab/Items/Equippables/Timer.prefab, Descension/Assets/Prefab/Items/Pickups/TimerPickupPrefab.prefab, Descension/Assets/ScriptableObject/Facts/WorldFactList.asset, Descension/Assets/Scripts/Environment/BombScript.cs
- Added alternate bomb dialogue depending on what items have been attached to it.
- Placed Explosives and Trigger pickups in level 4.
=> Final items implementation

Descension/Assets/Prefab/Actors/Enemies/EnemyPrefab.prefab, Descension/Assets/Scripts/Actor/AI/AIController.cs, Descension/Assets/Scripts/Items/ItemSpawner.cs, Descension/Assets/Scripts/Items/Pickups/ArrowsItem.cs, Descension/Assets/Scripts/Items/Pickups/BowItem.cs, Descension/Assets/Scripts/Items/Pickups/ExplosivesItem.cs, Descension/Assets/Scripts/Items/Pickups/HealthItem.cs, Descension/Assets/Scripts/Items/Pickups/PickItem.cs, Descension/Assets/Scripts/Items/Pickups/SwordItem.cs, Descension/Assets/Scripts/Items/Pickups/TimerItem.cs, Descension/Assets/Scripts/Items/Pickups/TriggerItem.cs
- Enemies have chance to drop random item on death.
- Default items to drop are Arrows, Potions, Picks, Sword, Bow.
- Set drop chance to 30% for all enemies, can be configured per enemy type or individually.
- Refactored ItemSpawner.
=> Implement Enemy Item Drops

Descension/Assets/Scenes/Levels/Level1-Perspective.unity, Descension/Assets/Scenes/Levels/Level2-Perspective.unity
Change all torches to last 15, move pick on level 1 to be easier to find and add health potions
=> Small fixes

Descension/Assets/Prefab/Actors/Enemies/PatrollingEnemy.prefab
=> adjusted melee enemy attack range

Descension/Assets/Prefab/Actors/Enemies/EnemyPrefab.prefab, Descension/Assets/Scripts/Actor/AI/AIController.cs, Descension/Assets/Scripts/Items/ItemShop.cs, Descension/Assets/Scripts/Items/Pickups/BowItem.cs, Descension/Assets/Scripts/Items/Pickups/PickItem.cs, Descension/Assets/Scripts/Items/Pickups/SwordItem.cs, Descension/Assets/Scripts/Managers/InventoryManager.cs
Hopefully improved the game performance.
- Limit FixedUpdate() logic in weapons and enemies to only run every 3 frames.
- Enemies only run state logic if within range of player.
- Set starting points for reticle and weapon item sprite.
=> Performance Improvements

Descension/Assets/Prefab/Actors/Enemies/EnemyPrefab.prefab, Descension/Assets/Prefab/Actors/Enemies/GuardEnemy.prefab, Descension/Assets/Prefab/Actors/Enemies/PatrollingEnemy.prefab, Descension/Assets/Prefab/Actors/Enemies/RangedPatrollingEnemy.prefab, Descension/Assets/Prefab/Actors/Projectiles/ArrowPrefab Slow.prefab, Descension/Assets/Prefab/Items/Equippables/Bow.prefab, Descension/Assets/Prefab/Items/Equippables/Sword.prefab, Descension/Assets/Scenes/TestScenes/CombatTestScene.unity, Descension/Assets/Scripts/Actor/AI/AIController.cs, Descension/Assets/Scripts/Actor/AI/AiCollision.cs, Descension/Assets/Scripts/Actor/AI/States/AIState.cs, Descension/Assets/Scripts/Actor/AI/States/MeleeAttackState.cs, Descension/Assets/Scripts/Actor/AI/States/RangeAttackState.cs, Descension/Assets/Scripts/Actor/Interface/IDamageable.cs, Descension/Assets/Scripts/Actor/Objects/Arrow.cs, Descension/Assets/Scripts/Actor/Objects/Projectile.cs, Descension/Assets/Scripts/Actor/Player/PlayerController.cs, Descension/Assets/Scripts/Environment/InspectableObject.cs, Descension/Assets/Scripts/Items/Pickups/BowItem.cs, Descension/Assets/Scripts/Items/Pickups/SwordItem.cs, Descension/Assets/Scripts/Managers/DialogueManager.cs, Descension/Assets/Scripts/Util/Helpers/Extensions.cs, Descension/ProjectSettings/NavMeshAreas.asset
- Added knockback to enemies and player on hit.
- Destroy inspectables after interaction.
=> Knockback and Enemy Adjustments

Descension/Assets/Prefab/Actors/PlayerPrefab.prefab, Descension/Assets/Prefab/GameManagers/ManagersPrefab.prefab, Descension/Assets/Scripts/Actor/Player/PlayerController.cs
- Fixed torch bug by moving GlobalPostProcessingPrefab from ManagersPrefab into PlayersPrefab, no idea why it suddenly wasn't working how it was.
- Added flickering effect to torch, and parameterized torch attributes.
NOTE: torch no longer turns on automatically when the first torch is picked up. If we want this to be the behaviour I can find a workaround, but some code changed I made to reduce computations and improve performance now prevent that behaviour.
=> fix torch bug, add flicker effect to torch

Descension/Assets/Prefab/Actors/Enemies/EnemyPrefab.prefab, Descension/Assets/Prefab/Actors/Enemies/GuardEnemy.prefab, Descension/Assets/Prefab/Actors/Enemies/PatrollingEnemy.prefab, Descension/Assets/Prefab/Actors/PlayerPrefab.prefab, Descension/Assets/Resources/Environment/Tilemaps/16x16 DungeonTileset II/0x72_DungeonTilesetII_v1.4.png.meta, Descension/Assets/Scripts/Actor/AI/AIController.cs, Descension/Assets/Scripts/Actor/AI/States/AIState.cs, Descension/Assets/Scripts/Actor/AI/States/ChaseLostState.cs, Descension/Assets/Scripts/Actor/AI/States/ChaseState.cs, Descension/Assets/Scripts/Actor/AI/States/MeleeAttackState.cs, Descension/Assets/Scripts/Actor/AI/States/PatrolState.cs, Descension/Assets/Scripts/Actor/Player/PlayerController.cs, Descension/Assets/Scripts/Items/Pickups/EquippableItem.cs, Descension/Assets/Scripts/Managers/InventoryManager.cs, Descension/Assets/Scripts/Util/Helpers/Extensions.cs
- Added basic sword animation to patrolling enemy (Can change the weapon sprite out if we want).
- Changed damage of patrolling enemy from 4 to 15.
- Added player death animation.
=> Add sword animation to patrolling enemy.

Descension/Assets/Scripts/Actor/AI/AIController.cs, Descension/Assets/Scripts/Actor/AI/States/BiteAttackState.cs, Descension/Assets/Scripts/Actor/AI/States/MeleeAttackState.cs, Descension/Assets/Scripts/Actor/Interface/UniqueMonoBehaviour.cs, Descension/Assets/Scripts/Actor/Player/PlayerController.cs, Descension/Assets/Scripts/Environment/RemovableRock.cs, Descension/Assets/Scripts/Items/ItemShop.cs, Descension/Assets/Scripts/Items/Pickups/EquippableItem.cs, Descension/Assets/Scripts/Items/Pickups/ExplosivesItem.cs, Descension/Assets/Scripts/Items/Pickups/TimerItem.cs, Descension/Assets/Scripts/Items/Pickups/TriggerItem.cs, Descension/Assets/Scripts/Managers/FactManager.cs, Descension/Assets/Scripts/Managers/GameManager.cs, Descension/Assets/Scripts/Managers/InventoryManager.cs, Descension/Assets/Scripts/Managers/UIManager.cs, Descension/Assets/Scripts/UI/Controllers/Codex/CodexController.cs, Descension/Assets/Scripts/UI/Controllers/Codex/CodexPageController.cs, Descension/Assets/Scripts/UI/Controllers/HUDController.cs, Descension/Assets/Scripts/UI/MenuUI/ProgressBar.cs, Descension/Assets/Scripts/Util/Editor/UniqueIdGenerator.cs, Descension/Assets/Scripts/Util/Helpers/GameDebug.cs, Descension/ProjectSettings/EditorBuildSettings.asset
Shouldn't have any conflicts.
- Made Id Generator more straight forward to use.
- Logging can be disabled by removing ENABLE_LOG_DEBUG symbol.
=> Improved Id Generator, made Logging disable-able

Descension/Assets/Scenes/Levels/Level1.unity, Descension/Assets/Scenes/Levels/Level2.unity, Descension/Assets/Scripts/Actor/Player/PlayerController.cs, Descension/Assets/Scripts/Environment/DescendHole.cs, Descension/Assets/Scripts/Items/Pickups/EquippableItem.cs, Descension/Assets/Scripts/Managers/GameManager.cs, Descension/Assets/Scripts/Managers/InventoryManager.cs, Descension/Assets/Scripts/Managers/SpawnManager.cs, Descension/Assets/Scripts/UI/Controllers/ButtonController/ChangeSceneButtonController.cs, Descension/Assets/Scripts/UI/Controllers/ButtonController/ReloadSceneButtonController.cs, Descension/Assets/Scripts/UI/Controllers/ButtonController/ReturnToMenuButtonController.cs, Descension/Assets/Scripts/UI/Controllers/ButtonController/UINavButtonController.cs, Descension/Assets/Scripts/Util/Enums/ClearCacheOptions.cs, Descension/Assets/Scripts/Util/Enums/ClearCacheOptions.cs.meta
- Refactored managers to make logic easier to follow. GameManager now calls the other managers on scene changes/resets etc to make it more logical to read.
- Fixed invisible weapon on level change from the presentation
- Fixed hole dialogue range bug
=> bug fixes and refactoring

Descension/Assets/Prefab/BombPrefab.prefab, Descension/Assets/Prefab/BombPrefab.prefab.meta, Descension/Assets/Prefab/Items/Equippables/Explosives.prefab, Descension/Assets/Prefab/Items/Equippables/Timer.prefab, Descension/Assets/Prefab/Items/Equippables/Trigger.prefab, Descension/Assets/Scripts/Actor/Player/PlayerController.cs, Descension/Assets/Scripts/Environment/BombScript.cs, Descension/Assets/Scripts/Items/Pickups/BowItem.cs, Descension/Assets/Scripts/Items/Pickups/ExplosivesItem.cs, Descension/Assets/Scripts/Items/Pickups/TimerItem.cs, Descension/Assets/Scripts/Items/Pickups/TriggerItem.cs, Descension/Assets/Scripts/Managers/DialogueManager.cs, Descension/Assets/Scripts/UI/Controllers/HUDController.cs
- Add some conditional assistive text to the bomb
- Add timed prompts that are displayed for a given amount of time before clearing/showing the next most important prompt
=> Add Bomb Prefab + Timed Prompts

Descension/Assets/Prefab/UI/HUD/GameHUD.prefab, Descension/Assets/Prefab/UI/UserInterfaceCanvas.prefab, Descension/Assets/Scripts/Managers/FactManager.cs, Descension/Assets/Scripts/UI/Controllers/Codex/CodexController.cs, Descension/Assets/Scripts/UI/Controllers/Codex/CodexPageController.cs, Descension/Assets/Scripts/UI/Controllers/HUDController.cs
=> Add Codex Notification

Descension/Assets/Scripts/Environment/Transport.cs
When activate timer bomb block shortcut out
=> block shortcut

Descension/Assets/Scenes/Levels/Level1.unity, Descension/Assets/Scenes/Levels/Level2.unity, Descension/Assets/Scripts/Environment/Message.cs
Make all messages.cs objects only only appear once
=> Unique messages
